In [1]:
import pandas as pd
import numpy as np
import scipy.stats as stats

In [2]:
df = pd.read_csv('insurance.csv')

In [3]:
df.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [4]:
df.shape

(1338, 7)

## question 1

The data is all about predicting the insurance charges for the person with respect to bmi and the person is smoker or not.The dataset is based on the supervised learning because the dataset is labeled and the dataset is having the target variable

## question 3

In [5]:
df.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [6]:
from sklearn.preprocessing import LabelEncoder
model=LabelEncoder()
df['sex']=model.fit_transform(df['sex'])
df['region']=model.fit_transform(df['sex'])
df['smoker']=model.fit_transform(df['smoker'])

In [7]:
df.head()

age  sex     bmi  children  smoker  region      charges
0   19    0  27.900         0       1       0  16884.92400
1   18    1  33.770         1       0       1   1725.55230
2   28    1  33.000         3       0       1   4449.46200
3   33    1  22.705         0       0       1  21984.47061
4   32    1  28.880         0       0       1   3866.85520

In [8]:
df.drop_duplicates(inplace=True)

In [9]:
df.shape

(1337, 7)

## question 4

We are now checking whether both the features are independent about each other or not using chi square test ( test for independence)


H0 : sex and smoking are independent


H1 : sex and smoking are not independent

In [10]:
obs_table=pd.crosstab(df['sex'],df['smoker'])
print("Observed frequencies")
print(obs_table)

Observed frequencies
smoker    0    1
sex             
0       547  115
1       516  159


In [11]:
obs=obs_table.values
print(obs)

[[547 115]
 [516 159]]


In [12]:
exp_t=stats.chi2_contingency(obs_table)
print(exp_t)

(7.469139330086637, 0.0062765550120107375, 1, array([[526.33208676, 135.66791324],
       [536.66791324, 138.33208676]]))


In [13]:
dof=exp_t[2]
exp=exp_t[3]
print("Expected frequencies")
print(exp)

Expected frequencies
[[526.33208676 135.66791324]
 [536.66791324 138.33208676]]


In [14]:
chi_squared_stat = (((obs-exp)**2)/exp).sum().sum()
print("chi square statistic")
print(chi_squared_stat)

chi square statistic
7.844077785733106


In [15]:
crit=stats.chi2.ppf(q = 0.95,df = dof) 
print("critical value for respective confidence interval and degree of freedom")
print(crit)

critical value for respective confidence interval and degree of freedom
3.841458820694124


In [16]:
p_value = 1 - stats.chi2.cdf(x=chi_squared_stat,  
                             df=dof)
print("P value")
print(p_value)

P value
0.005098746217145678


In [17]:
if p_value < 0.05:   
    print(" we are rejecting null hypothesis")
else:
    print("we are accepting null hypothesis")

 we are rejecting null hypothesis


### Sex and smoking are not independent

## question 5

In [18]:
X=df.drop('charges',axis=1)
cnames=list(X.columns)

In [19]:
cnames

['age', 'sex', 'bmi', 'children', 'smoker', 'region']

In [20]:
for i in cnames:
    for j in cnames:
        if(i!=j):
            obs_table=pd.crosstab(df[i],df[j])
            obs=obs_table.values
            exp_t=stats.chi2_contingency(obs_table)
            dof=exp_t[2]
            exp=exp_t[3]
            chi_squared_stat = (((obs-exp)**2)/exp).sum().sum()
            crit=stats.chi2.ppf(q = 0.95,df = dof) 
            p_value = 1 - stats.chi2.cdf(x=chi_squared_stat,df=dof)
            if p_value < 0.05:
                print(f" {i} and  {j} are not independent")
            else:
                print(f" {i} and  {j} are independent")

 age and  sex are independent
 age and  bmi are independent
 age and  children are not independent
 age and  smoker are independent
 age and  region are independent
 sex and  age are independent
 sex and  bmi are independent
 sex and  children are independent
 sex and  smoker are not independent
 sex and  region are not independent
 bmi and  age are independent
 bmi and  sex are independent
 bmi and  children are independent
 bmi and  smoker are independent
 bmi and  region are independent
 children and  age are not independent
 children and  sex are independent
 children and  bmi are independent
 children and  smoker are independent
 children and  region are independent
 smoker and  age are independent
 smoker and  sex are not independent
 smoker and  bmi are independent
 smoker and  children are independent
 smoker and  region are not independent
 region and  age are independent
 region and  sex are not independent
 region and  bmi are independent
 region and  children are independen

Not all the regressor variables are independent of each other, only bmi is independent with all features

## question 6

In [21]:
j="charges"
for i in cnames:
    obs_table=pd.crosstab(df[i],df[j])
    obs=obs_table.values
    exp_t=stats.chi2_contingency(obs_table)
    dof=exp_t[2]
    exp=exp_t[3]
    chi_squared_stat = (((obs-exp)**2)/exp).sum().sum()
    crit=stats.chi2.ppf(q = 0.95,df = dof) 
    p_value = 1 - stats.chi2.cdf(x=chi_squared_stat,df=dof)
    if p_value < 0.05:
        print(f" {i} and  {j} are not independent")
    else:
        print(f" {i} and  {j} are independent")

 age and  charges are independent
 sex and  charges are independent
 bmi and  charges are independent
 children and  charges are independent
 smoker and  charges are independent
 region and  charges are independent


response and regressors are independent of each other

## question 7

In [22]:
X=df.drop('charges',axis=1)
y=df['charges']

In [23]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=3)

In [24]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(X_train,y_train)
pred=model.predict(X_test)

In [25]:
model.intercept_

-12004.987401392233

In [26]:
model.coef_

array([  261.02035669,  -113.22506984,   316.78476878,   464.61064522,
       24239.42001414,  -113.22506984])

## question 8

In [27]:
model.score(X_test,y_test)

0.7604691935331385

## question 9

In [28]:
pred1=model.predict([[29,0,28,1,1,0]])

C:\Users\Lucifer.LAPTOP-19ER5RAR\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


In [29]:
pred1

array([29138.60712805])

insurance chagers : 29138.60712805

## question 10

In [30]:
from sklearn.metrics import mean_absolute_percentage_error

In [31]:
error=mean_absolute_percentage_error(y_test,pred)

In [32]:
error

0.39702898287144683

## question 11

In [33]:
y_mean=np.mean(y)
print(y_mean)

13279.121486655948
